/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExpeditionsRouteImport } from './routes/expeditions'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as RoutesLineMapRouteImport } from './routes/routes-line-map'
import { Route as TalentTrainingDesignRouteImport } from './routes/talent-training-design'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrainingCoursesRouteImport } from './routes/training-courses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRoute = ExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesLineMapRoute = RoutesLineMapRouteImport.update({
  id: '/routes-line-map',
  path: '/routes-line-map',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTrainingDesignRoute = TalentTrainingDesignRouteImport.update({
  id: '/talent-training-design',
  path: '/talent-training-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCoursesRoute = TrainingCoursesRouteImport.update({
  id: '/training-courses',
  path: '/training-courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/clubs': typeof ClubsRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/expeditions': typeof ExpeditionsRoute
  '/gallery': typeof GalleryRoute
  '/routes-line-map': typeof RoutesLineMapRoute
  '/talent-training-design': typeof TalentTrainingDesignRoute
  '/testimonials': typeof TestimonialsRoute
  '/training-courses': typeof TrainingCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/clubs': typeof ClubsRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/expeditions': typeof ExpeditionsRoute
  '/gallery': typeof GalleryRoute
  '/routes-line-map': typeof RoutesLineMapRoute
  '/talent-training-design': typeof TalentTrainingDesignRoute
  '/testimonials': typeof TestimonialsRoute
  '/training-courses': typeof TrainingCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/clubs': typeof ClubsRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/expeditions': typeof ExpeditionsRoute
  '/gallery': typeof GalleryRoute
  '/routes-line-map': typeof RoutesLineMapRoute
  '/talent-training-design': typeof TalentTrainingDesignRoute
  '/testimonials': typeof TestimonialsRoute
  '/training-courses': typeof TrainingCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/clubs'
    | '/coaching'
    | '/contact'
    | '/expeditions'
    | '/gallery'
    | '/routes-line-map'
    | '/talent-training-design'
    | '/testimonials'
    | '/training-courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/clubs'
    | '/coaching'
    | '/contact'
    | '/expeditions'
    | '/gallery'
    | '/routes-line-map'
    | '/talent-training-design'
    | '/testimonials'
    | '/training-courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/clubs'
    | '/coaching'
    | '/contact'
    | '/expeditions'
    | '/gallery'
    | '/routes-line-map'
    | '/talent-training-design'
    | '/testimonials'
    | '/training-courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  ClubsRoute: typeof ClubsRoute
  CoachingRoute: typeof CoachingRoute
  ContactRoute: typeof ContactRoute
  ExpeditionsRoute: typeof ExpeditionsRoute
  GalleryRoute: typeof GalleryRoute
  RoutesLineMapRoute: typeof RoutesLineMapRoute
  TalentTrainingDesignRoute: typeof TalentTrainingDesignRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrainingCoursesRoute: typeof TrainingCoursesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes-line-map': {
      id: '/routes-line-map'
      path: '/routes-line-map'
      fullPath: '/routes-line-map'
      preLoaderRoute: typeof RoutesLineMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-training-design': {
      id: '/talent-training-design'
      path: '/talent-training-design'
      fullPath: '/talent-training-design'
      preLoaderRoute: typeof TalentTrainingDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-courses': {
      id: '/training-courses'
      path: '/training-courses'
      fullPath: '/training-courses'
      preLoaderRoute: typeof TrainingCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  ClubsRoute: ClubsRoute,
  CoachingRoute: CoachingRoute,
  ContactRoute: ContactRoute,
  ExpeditionsRoute: ExpeditionsRoute,
  GalleryRoute: GalleryRoute,
  RoutesLineMapRoute: RoutesLineMapRoute,
  TalentTrainingDesignRoute: TalentTrainingDesignRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrainingCoursesRoute: TrainingCoursesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
